name: ASP.NET CI
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-Nuget@v1
    - run: nuget restore $Env:GITHUB_WORKSPACE\FeedbackMessages\FeedbackMessages.csproj
    - uses: warrenbuckley/Setup-MSBuild@v1
    - run: MSBuild.exe $Env:GITHUB_WORKSPACE\FeedbackMessages\FeedbackMessages.csproj -p:Configuration=Release
      timeout-minutes: 5
